### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by sdfizzz** [JohnAlbin/styled-media-queries#1]
When I try to build my project after added styled-media-queries I get an error:
$ yarn build
yarn build v0.23.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/styled-media-query/src/index.js:20

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.

**Comment by iamdanthedev** [comment]
Hi
To fix the problem you could just replace the function from the package with this one

```
const mediaQuery = (...query) => (...rules) => css`
  @media ${css`${query}`} {
    ${css`${rules}`};
  }
`;

```
  
Or see my pr

**Comment by rogeriocsilva** [comment]
Hey man, I'm having some problems using this method with nested conditions or variables. 

Example: ``
${media.mobile`
    background-color: ${Theme.bodyBackground};
`}
`` will output the `#FFF` instead of `background-color: #FFF`.

**Comment by rogeriocsilva** [comment]
fixed, see my pr :smile:
